version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend # Corrected to match the actual filename
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: